config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    root to: "home#index"
    
    get 'home/index'

    get 'terms' => 'pages#terms'
    get 'about' => 'pages#about'

    resource :contacts, only: [ :new, :create], path_names: { :new =>  '' }
    resources :articles do
    resource :comments, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true

  has_many :comments, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,  presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parametrs, if: :devise_controller?

  private
  
def configure_permitted_parametrs
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   # devise_parameter_sanitizer.for(:sign_in) << :username
   # devise_parameter_sanitizer.for(:account_update)  << :username
end 



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end


  def create
    @article = Article.new(article_params)
    @article.articlename = current_user.username
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end  
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy

    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path

  end

    private
      def article_params
        params.require(:article).permit(:title, :text)
      end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    coment = @article.comments.new 
    coment.author = current_user.username
    coment.body = comment_params[:body]
    coment.save

    redirect_to article_path(@article)
  end
private
  def comment_params
    params.require(:comment).permit( :body)

  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end  
  end

    private

    def contact_params
      params.require(:contact).permit(:email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/create.html.erb
<h1>Thanks! for article</h1>

<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>

  <% if @article && @article.errors.any?%>
  <p>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>

      <% end %>
    </ul>
  </p>
<% end %>  
 
  <p> 
    <%= f.label :title, class: "form-label" %> <br />
    <%= f.text_field :title, class: "form-control form-control-sm" %>
  </p>

  <p> 
    <%= f.label :text, class: "form-label" %> <br />
    <%= f.text_area :text, class: "form-control form-control-sm" %>
  </p>

  <%= f.submit class: "btn btn-primary" %>

<%  end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <h3><%= article.title %></h3>
  <p><%= article.text %></p>
  <p><i>Author: <%= article.articlename%> at created: <%= article.created_at%></i></p>
  <p><%= link_to 'Show',article_path(article) %></p>
  <hr/>
<% end %>
<br />
<% if user_signed_in? == false  %>
  <p>
      Please <%= link_to "Sign in", new_user_session_path %> or <%= link_to "Registered", new_user_registration_path %> to leave Articles new
  </p>
<% else %>
  <%= link_to "Articles new", new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h2>New articles</h2>

<%= form_for :article, url: articles_path do |f| %>

  <% if @article && @article.errors.any?%>
  <p>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>

      <% end %>
    </ul>
  </p>
<% end %>  
 
  <p> 
    <%= f.label :title, class: "form-label" %> <br />
    <%= f.text_field :title, class: "form-control form-control-sm" %>
  </p>

  <p> 
    <%= f.label :text, class: "form-label"  %> <br />
    <%= f.text_area :text, class: "form-control form-control-sm" %>
  </p>

  <%= f.submit class: "btn btn-primary"%>

<%  end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p>
    <%= @article.text %>
</p>
<p><i>Author: <%= @article.articlename%> at created: <%= @article.created_at%></i></p>
<br/>
<% if user_signed_in? && @article.articlename == current_user.username %>
  <p><%= link_to 'Edit', edit_article_path(@article) %>|
  <%= link_to 'Destroy', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'} %></p>
<% end %>
<h4>Comments:</h4>

<p>
  <% @article.comments.each do |comment| %>
    <p><%= comment.body %></p>
    <p><i>Said <%= comment.author %> at <%= comment.created_at %></i></p>
    <hr/>
  <% end %>

</p>

<% if user_signed_in? %>
<!--   <h4>Add comment</h4>
 -->    <%= form_for ([@article, @article.comments.build]) do |f| %>
     
      <!-- <p> 
        <%= f.label :author %> <br />
        <%= f.text_field :author %>
      </p> -->

      <p>
<!--   <%= f.label :body %> <br />
 -->    <%= f.text_area :body, class: "form-control form-control-sm", placeholder: "Your comment" %>
      </p>

      <%= f.submit 'Enter comment', class: "btn btn-primary" %>
      <%  end %>
<% else %>
  <p>
      Please <%= link_to "Sign in", new_user_session_path %> or <%= link_to "Registered", new_user_registration_path %> to leave comments
  </p>
  
<% end %>

app/views/contacts/create.html.erb
<h1>Thanks!</h1>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
<% if @contact && @contact.errors.any? %>
  <p>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>

      <% end %>
    </ul>
  </p>
<% end %>  
 
  <p> 
    <%= f.label :email %> <br />
    <%= f.text_field :email %>
  </p>

  <p> 
    <%= f.label :message %> <br />
    <%= f.text_area :message %>
  </p>

  <%= f.submit 'Send Message' %>

<%  end %>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>We are nice to see you body</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog on NEC</title>
    <!-- Bootstrap CSS (jsDelivr CDN) -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
  <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">

        <div class="row"> 

          <div class="col-8">  
           <ul class="nav nav-tabs">
              
              <li class="nav-item">
                <%= link_to "Blog on NEC", home_index_path, class: "nav-link #{request.fullpath == home_index_path ? 'active' : '' }" %>
              </li>
              <li class="nav-item">
                <%= link_to "Articles", articles_path, class: "nav-link #{request.fullpath == articles_path ? 'active' : '' }" %>
              </li>
              <li class="nav-item">
                <%= link_to "Articles new", new_article_path, class: "nav-link #{
                 if user_signed_in?
                      request.fullpath == new_article_path ? 'active' : '' 
                  else 
                    'disabled'
                  end }" %>
              </li> 

              <li class="nav-item">
                <%= link_to "Contact us", new_contacts_path, class: "nav-link #{request.fullpath == new_contacts_path ? 'active' : '' }" %>
              </li>

              <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link #{request.fullpath == about_path ? 'active' : '' }" %>
              </li>

              <li class="nav-item">
                <%= link_to "Terms", terms_path, class: "nav-link #{request.fullpath == terms_path ? 'active' : '' }" %>
              </li>             
            </ul>
          </div>
          <div class="col-4">
            <ul class="nav nav-tabs justify-content-end">
                
              <% if user_signed_in? %>

                <li class="nav-item">
                  <%= link_to "Hi, #{current_user.username} !", edit_user_registration_path, class: "nav-link" %>
                </li>

                <li class="nav-item">              
                  <%= link_to 'Sign out',destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>

                <% else %>

                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
                </li>

                <% end %>
              </ul>
            </div>


        

                 <!-- <div id="user_nav"> 
                  <% if user_signed_in? %>
                    Hello  <i><%= current_user.username %></i> , Not you? 
                    <%= link_to 'Sign out',destroy_user_session_path, method: :delete %>
                  <% else %>
                    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
                  <% end %>
                 </div>  -->
 
            

        </div>
       <!--  <%= request.fullpath %>  вызов текущего path/url
        <%= home_index_path %> -->


       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
</br>
<h3> <b> Quality Standards </b>

Every article you see has several people behind it working to make sure that it is accurate, understandable, helpful, and reflective of our principles and editorial guidelines.

Our editors review and approve all article ideas independently. Each new article is rigorously reviewed and edited by our editorial team before it is published to our site. All visuals, tools, and videos are subject to the same approval process. </h3>

app/views/pages/terms.html.erb
<h1>Terms(Условия использования):</h1>
<h3> Overview

ThoughtCo.com and its affiliated sites (collectively, the “Site”) are Dotdash brands, owned and operated by About, Inc. and its affiliates ("ThoughtCo", the "Company", "we", or "us"). Access to and use of the Site is subject to these terms and conditions of use (“Terms of Use”). </h3>